[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "cacert",
  "glib",
  "dbus",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXcursor",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libXrender",
  "xorg.libXtst",
  "xorg.libxcb",
  "xorg.libXScrnSaver",
  "alsa-lib",
  "atk",
  "cups",
  "gtk3",
  "pango",
  "libdrm",
  "mesa",
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/root/.nix-profile/bin/chromium"